# Use the official Ubuntu 24.04 base image
FROM ubuntu:24.04

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install Java (OpenJDK),Apache Ant, zip, unzip, AWS CLI
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-21-jdk \
    ant \
    zip \
    unzip \
	openssh-client \
    ca-certificates \
    curl \
    git \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf awscliv2.zip ./aws \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Verify installations
RUN java -version && ant -version && aws --version

# Create a group and user matching UID 110
RUN groupadd -g 114 jenkins && \
    useradd -u 110 -g jenkins -m -s /bin/bash jenkins

# (Optional) Switch to this user
#USER 110


# Set default working directory
WORKDIR /opt/IBM/SMP

# Need libs in lib dir src=/maximo/lib  target="/opt/IBM/SMP/maximo/applications/maximo/lib" />
COPY lib ./maximo/applications/maximo/lib

# Need classes in dep.bo src=/maximo/classes/ target=/opt/IBM/SMP/maximo/applications/maximo/businessobjects
COPY classes/businessobjects ./maximo/applications/maximo/businessobjects

# Need build jars in dep.dir src=/maximo/buildJars target=/opt/IBM/SMP/buildJars
COPY buildJars ./buildJars

#Copy source for now - testing
#WORKDIR /fuj/workspace
#COPY VSBAMAS ./VSBAMAS

#Copy tools jars
COPY customJars ./customJars

